# AWS playbook
---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: aws_key          
    region: ap-south-1
    image: ami-03f4878755434977f
    instance_type: t2.micro
    sec_group: "launch-wizard-3"
    access_key: "AKIARQON6MXQJONTFL7N"
    secret_key: "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"
    subnet_id: "subnet-0bc0626ad9cacf827"

  tasks:
    - amazon.aws.ec2_instance:
        name: "my_instance2"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}" 
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        network:
          assign_public_ip: true
        image_id: "{{ image }}"
        count: 2
        region:  "{{ region }}"

