# AWS playbook
---

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
      - instance_vars.yml

  tasks:
    - amazon.aws.ec2_instance:
        name: "my_instance2"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}" 
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        network:
          assign_public_ip: true
        image_id: "{{ image }}"
        count: 2
        region:  "{{ region }}"

