---
- name: Setting up CMS Application on AWS EC2 instance
  hosts: my_servers
  become: yes
  gather_facts: yes
  remote_user: ubuntu
  # tags: main


  tasks:

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      tags: apt

    - name: Installing MySQL server by apt
      ansible.builtin.apt:
        name: mysql-server
        state: present
      tags: apt

    - name: Installing Python3 pip
      ansible.builtin.apt:
        name: python-pip
        state: present
      tags: apt

    - name: Install Nginx from apt
      ansible.builtin.apt:
        name: nginx
        state: present
      become: yes
      tags: apt


    - name: Install gedit from apt
      ansible.builtin.apt:
        name: gedit
        state: present
      become: yes
      tags: apt

    - name: Install htop from apt
      ansible.builtin.apt:
        name: htop
        state: present
      become: yes
      tags: apt

    - name: Install tree from apt
      ansible.builtin.apt:
        name: tree
        state: present
      become: yes
      tags: apt

    # Step3 --> Application Setup

    - name: Create CMS directory
      ansible.builtin.file:
        path: /home/ubuntu/CMS
        state: directory
      tags: cms

    - name: Clone a github repository
      ansible.builtin.git:
        repo: https://github.com/lokeshdangii/CMS.git
        dest: /home/ubuntu/CMS
        clone: yes
        update: yes
      tags: cms

    # - name: Run CMS Application
    #   ansible.builtin.command: "python3 /home/ubuntu/CMS/app.py &"
    #   tags: cms

    - name: Print CMS is running
      debug:
        msg: "CMS Application is availabe on port"


    # pip packages
    - name: Install mysqlclient module from pip
      ansible.builtin.pip:
        name: mysqlclient
        state: present
      become: true
      tags: pip

    - name: Install required Python packages
      pip:
        name:
          - Flask==3.0.0
      tags: pip