---
# tasks file for packages_setup
#
    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: "{{ apt_update_cache_duration }}"
        force_apt_get: true

    - name: Installing required packages
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: present
      become: true
