---

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
      - vpc_vars.yml

  tasks:
    - name: create a VPC with dedicated tenancy and a couple of tags
      amazon.aws.ec2_vpc_net:
        name: Demo_VPC_By_Lokesh
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        cidr_block: 10.0.0.0/16
        region: ap-south-1
        tags:
          module: ec2_vpc_net
          this: works
        tenancy: default