---

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
      - vpc_vars.yml
    
  tasks:
    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: vpc-0e7b4e3d5d827e380
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: ap-south-1
        state: present
      register: igw