---

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vpc_vars.yml

  tasks:
    - name: create a VPC with dedicated tenancy and a couple of tags
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        cidr_block: "{{ cidr_block_vpc }}"
        region: "{{ region }}"
        tags:
          module: ec2_vpc_net
          this: works
        tenancy: default
      register: created_vpc

    - name: Create subnet for VPC
      amazon.aws.ec2_vpc_subnet:
        state: present
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        vpc_id: "{{ created_vpc.vpc.id }}"
        cidr: "{{ cidr_subnet }}"
        region: "{{ region }}"
        tags:
          Name: "{{ subnet_name }}"
      register: demo_subnet

    - name: Create Internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ created_vpc.vpc.id }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "{{ igw_name }}"
      register: igw

    - name: Set up public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ created_vpc.vpc.id }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        tags:
          Name: "{{ rt_name }}"
        subnets:
          - "{{ demo_subnet.subnet.id }}"
        routes:
          - dest: "{{ route_dest }}"
            gateway_id: "{{ igw.gateway_id }}"
