---
- name: Setting up CMS Application on AWS EC2 instance
  hosts: my_servers
  become: yes
  gather_facts: yes
  remote_user: ubuntu

# Step 1 --> Installing and Updating packages
  tasks:
    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

    - name: Installing python3 venv
      ansible.builtin.apt:
        name: python3-venv
        state: present

    - name: Installing MySQL server
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Installing Python3 pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Installing required Python packages
      ansible.builtin.pip:
        name:
          - blinker==1.6.3
          - click==8.1.7
          - Flask==3.0.0
          - flask-paginate==2023.10.24
          - itsdangerous==2.1.2
          - Jinja2==3.1.2
          - MarkupSafe==2.1.3
          - mysql-connector==2.2.9
          - mysql-connector-python==8.2.0
          - protobuf==4.21.12
          - Werkzeug==3.0.1

# Step2 -->  Database setup for the CMS Application

    - name: Install build dependencies for mysqlclient
      ansible.builtin.apt:
        name:
          - libmysqlclient-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-dev
          - pkg-config
      become: true

    - name: Install MySQL Python module
      ansible.builtin.pip:
        name: mysqlclient
        state: present
      become: true
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Create new databases with name cardb
      community.mysql.mysql_db:
        name:
          - cardb
        state: present

    - name: Copy file cardb.sql to remote hosts
      ansible.builtin.copy:
        src: /home/lokesh/Desktop/Decode/Ansible/ansible_quickstart/cardb.sql
        dest: /home/ubuntu/
      become: true

    - name: Import Database Schema
      shell: "sudo mysql cardb < cardb.sql"
      become_user: root

    - name: Update MySQL User Password
      shell: "sudo mysql -e 'ALTER USER \"root\"@\"localhost\" IDENTIFIED WITH mysql_native_password BY \"root\";'"
      become_user: root

    - name: Print Database Setup Completed Message
      ansible.builtin.debug:
        msg: "Database setup completed successfully."

# Step3 --> Application Setup

    - name: Create CMS directory
      ansible.builtin.file:
        path: /home/ubuntu/CMS
        state: directory

    - name: Clone a github repository
      ansible.builtin.git:
        repo: https://github.com/lokeshdangii/CMS.git
        dest: /home/ubuntu/CMS
        clone: yes
        update: yes

    - name: Run CMS Application
      ansible.builtin.command: "python3 /home/ubuntu/CMS/app.py &"
