---
# tasks file for nginx_setup
#
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: yes

    - name: Copy Nginx configuration file
      ansible.builtin.copy:
        src: /home/lokesh/Desktop/Decode/AWS_Script/Gunicorn/cms
        dest: /etc/nginx/sites-available/
        mode: '0644'
      become: yes

    - name: Create a symbolic link to enable the configuration using command module
      ansible.builtin.command: ln -s /etc/nginx/sites-available/cms /etc/nginx/sites-enabled/
      become: yes

    - name: Unlink the default one
      ansible.builtin.command: unlink /etc/nginx/sites-enabled/default
      become: yes

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
      become: yes

    - name: Print Nginx Setup Completed 
      ansible.builtin.debug:
        msg: "CMS application is served successfully on nginx. Access the application by server public IP Address"
