---
# tasks file for nginx_setup
#
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: yes

    - name: Copy Nginx configuration file
      ansible.builtin.template:
        src: nginx_config.j2
        dest: "{{ nginx_config_dest }}"
        mode: '0644'
      become: yes

    - name: Create a symbolic link to enable the configuration using command module
      ansible.builtin.command: ln -s "{{ nginx_config_dest }}" "{{ nginx_sites_enabled }}"
      become: yes

    - name: Unlink the default one
      ansible.builtin.command: unlink "{{ nginx_sites_enabled }}"/default
      become: yes

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
      become: yes

    - name: Print Nginx Setup Completed 
      ansible.builtin.debug:
        msg: "CMS application is served successfully on nginx. Access the application by server public IP Address"
