---
# tasks file for database_setup
# Step2 -->  Database setup for the CMS Application

    - name: Install MySQL Python module
      ansible.builtin.pip:
        name: mysqlclient
        state: present
      become: true
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Create new databases with name cardb
      community.mysql.mysql_db:
        name:
          - cardb
        state: present

    - name: Copy file cardb.sql to remote hosts
      ansible.builtin.copy:
        src: files/cardb.sql
        dest: "{{ sql_file_dest_path }}"
      become: true

    - name: Import Database Schema
      shell: "sudo mysql {{ mysql_db_name }} < /home/ubuntu/cardb.sql"
      become_user: root

    - name: Update MySQL User Password
      shell: "sudo mysql -e 'ALTER USER \"root\"@\"localhost\" IDENTIFIED WITH mysql_native_password BY \"root\";'"
      become_user: root

    - name: Print Database Setup Completed Message
      ansible.builtin.debug:
        msg: "Database setup completed successfully."
